/*******************************************************************************
 * Copyright (c) 2013 United States Government as represented by the 
 * Administrator of the National Aeronautics and Space Administration. 
 * All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package gov.nasa.ensemble.ui.databinding.widgets.customization;

import gov.nasa.ensemble.ui.databinding.validation.ISimpleValidator;

import java.util.List;

/**
 * Customize the auto generated widget for a given model.
 * @author tecohen
 *
 */
public interface ICustomization {

	/**
	 * Retrieve an order-specific list of field customization for the child fields to be displayed.
	 * If a field is not included in this list, it will not be included in the autogenerated widget.
	 * @return
	 */
	public List<FieldCustomization> getFields();
	
	
	/**
	 * Retrieve a cross-field validator for the entire model.  This can return null.
	 * @return
	 */
	public ISimpleValidator getValidator();
	
	/**
	 * Get the field customization indicated by the key
	 * @param key
	 * @return
	 */
	public FieldCustomization getField(String key);
	
	/**
	 * Get an ordered list of groups
	 * @return
	 */
	public List<GroupCustomization> getGroups();
	
	/**
	 * Get a particular group
	 * @param key
	 * @return
	 */
	public GroupCustomization getGroup(String key);
	
	/**
	 * Get an ordered list of fields and groups; supports interleaving of both.
	 * If you have no groups or no standalone fields you do not have to use this.
	 * @return
	 */
	public List<String> getOrderedWidgets();
	
}
