#ifndef rapid_AthleteDefs_idl
#define rapid_AthleteDefs_idl

/*
 * Copyright (c) 2009 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "BaseTypes.idl"

/**
 * \file
 *
 * \brief Defines constants related to the ATHLETE robot as a convenience for programmers.
 *
 * \ingroup idlfiles
 */
module rapid {

    const long ATHLETE_LEG_1 = 0;
    const long ATHLETE_LEG_2 = 1;
    const long ATHLETE_LEG_3 = 2;
    const long ATHLETE_LEG_4 = 3;
    const long ATHLETE_LEG_5 = 4;
    const long ATHLETE_LEG_6 = 5;

    const long ATHLETE_AUX_LEG_ID_INDEX = 0;
    const long ATHLETE_AUX_MOTOR_ANGLE_INDEX = 1;

    const String32 ATHLETE_SUBSYS_NAME_EHA = "ATHLETE_EHA";
    const String32 ATHLETE_SUBSYS_NAME_FORCE_TORQUE = "ATHLETE_FORCE_TORQUE";
    const String32 ATHLETE_SUBSYS_NAME_BATT = "ATHLETE_BATTERY";

    const String16 ATHLETE_HEADING_RAD_KEY = "ATHLETE_HEADING_RAD";
    const String16 ATHLETE_BODY_TILT_KEY = "ATHLETE_BODY_TILT";
    const String16 ATHLETE_BODY_ROLL_KEY = "ATHLETE_BODY_ROLL";
    const String16 ATHLETE_BODY_PITCH_KEY = "ATHLETE_BODY_PITCH";
    const String16 ATHLETE_ODOMETRY_KEY = "ATHLETE_ODOMETRY";

    const String16 ATHLETE_HEADING_FLOAT = "ATHLETE_HEADING_RAD__FLOAT__";
    const String16 ATHLETE_TILT_FLOAT = "ATHLETE_BODY_TILT__FLOAT__";
    const String16 ATHLETE_ROLL_FLOAT = "ATHLETE_BODY_ROLL__FLOAT__";
    const String16 ATHLETE_PITCH_FLOAT = "ATHLETE_BODY_PITCH__FLOAT__";
    const String16 ATHLETE_ODOMETRY_FLOAT = "ATHLETE_ODOMETRY__FLOAT__";

    const String16 ATHLETE_PROC_ID_INT = "ATHLETE_PROCESSOR_ID__INT__";
    const String16 ATHLETE_CAM_REFP_X_FLOAT = "ATHLETE_CAM_REFP_X__FLOAT__";
    const String16 ATHLETE_CAM_REFP_Y_FLOAT = "ATHLETE_CAM_REFP_Y__FLOAT__";
    const String16 ATHLETE_CAM_REFP_Z_FLOAT = "ATHLETE_CAM_REFP_Z__FLOAT__";
    const String16 ATHLETE_CAM_REFQ_P_FLOAT = "ATHLETE_CAM_REFQ_P__FLOAT__";
    const String16 ATHLETE_CAM_REFQ_Y_FLOAT = "ATHLETE_CAM_REFQ_Y__FLOAT__";
    const String16 ATHLETE_CAM_REFQ_R_FLOAT = "ATHLETE_CAM_REFQ_R__FLOAT__";
    const String16 ATHLETE_CAM_REFQ_W_FLOAT = "ATHLETE_CAM_REFQ_W__FLOAT__";
    const String16 ATHLETE_CAM_V2_FLOAT = "ATHLETE_CAM_V2__FLOAT__";

    const String16 ATHLETE_CAM_IMG_ACQ_TIME_FLOAT = "ATHLETE_CAM_IMGACQTIM__FLOAT__";

    const String16 ATHLETE_BATT1_INT = "ATHLETE_BATT1__INT__";
    const String16 ATHLETE_BATT2_INT = "ATHLETE_BATT2__INT__";
    const String16 ATHLETE_BATT3_INT = "ATHLETE_BATT3__INT__";
    const String16 ATHLETE_BATT4_INT = "ATHLETE_BATT4__INT__";
    const String16 ATHLETE_BATT5_INT = "ATHLETE_BATT5__INT__";
    const String16 ATHLETE_BATT6_INT = "ATHLETE_BATT6__INT__";
    const String16 ATHLETE_BATTV12_INT = "ATHLETE_BATTV12__INT__";
    const String16 ATHLETE_BATTV24_INT = "ATHLETE_BATTV24__INT__";
    const String16 ATHLETE_BATTV48_INT = "ATHLETE_BATTV48__INT__";
    const String16 ATHLETE_BATTSOC_INT = "ATHLETE_BATTSOC__INT__";

    const String32 ATHLETE_NUM_LEGS = "ATHLETE_NUM_LEGS";
    const String32 ATHLETE_DRIVE_FACE = "ATHLETE_DRIVE_FACE";
    const String32 ATHLETE_NUM_JOINTS = "ATHLETE_NUM_JOINTS";

    const String32 ATHLETE_CAMERA_SET = "ATHLETE_CAMERA_SET";
    const String32 ATHLETE_CAMERA_SELECTION = "ATHLETE_CAMERA_SELECTION";
    const String32 ATHLETE_CAMERA_LEG = "ATHLETE_CAMERA_LEG";

    //@copy-declaration /** Articulation indexes for the JointData arrays. */
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_HIP_YAW     = 0;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_HIP_PITCH   = 1;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_THIGH_PITCH = 2;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_KNEE_PITCH  = 3;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_KNEE_ROLL   = 4;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_ANKLE_PITCH = 5;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_ANKLE_ROLL  = 6;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_GRIPPER     = 7;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_WHEEL       = 8;
    const long ATHLETE_ARTIC_JOINTDATA_INDEX_DOCK        = 9;

    const String16 FLOAT_TYPE_KEY = "__FLOAT__";
    const String16 INT_TYPE_KEY = "__INT__";

};

#endif // rapid_AthleteDefs_idl
