#ifndef rapid_ext_VEStopConfig_idl
#define rapid_ext_VEStopConfig_idl

/*
 * Copyright (c) 2012 United States Government as represented by the
 * Administrator of the National Aeronautics and Space Administration.
 * All Rights Reserved.
 */

#include "Message.idl"
#include "BaseTypes.idl"

module rapid
{
  module ext
  {
    //@copy-c-declaration class VEStopConfigTypeSupport;
    //@copy-c-declaration class VEStopConfigDataWriter;
    //@copy-c-declaration class VEStopConfigDataReader;
    //@copy-c-declaration struct VEStopConfigSeq;

    valuetype VEStopConfig : Message
    {
      //@copy-c-declaration #if RTI_DDS_VERSION_MAJOR < 4 || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR < 5) || (RTI_DDS_VERSION_MAJOR == 4  && RTI_DDS_VERSION_MINOR  == 5 && RTI_DDS_VERSION_RELEASE != 'f' )
      //@copy-c-declaration typedef VEStopConfigTypeSupport TypeSupport;
      //@copy-c-declaration typedef VEStopConfigDataWriter DataWriter;
      //@copy-c-declaration typedef VEStopConfigDataReader DataReader;
      //@copy-c-declaration typedef VEStopConfigSeq Seq;
      //@copy-c-declaration #endif
      //@copy-c-declaration typedef VEStopConfig Type;

      //@copy-declaration /** The evaluation interval for the trajectory sequences in microsec. Typically 0.2s. */
      public long long evaluationInterval;
    };
  };
};

#endif // rapid_ext_VEStopConfig_idl
