#ifndef rapid_ext_traclabs_NoticeAck_idl
#define rapid_ext_traclabs_NoticeAck_idl

#include "Message.idl"

module rapid
{
  module ext
  {
    module traclabs
    {
    
      valuetype NoticeAck : Message {

        //@copy-c-declaration typedef NoticeAck Type;

        //@copy /** noticeId of notice being acknowledged */
        public String16  noticeId;  
        //@copy /** id of user who acknowledged the notice */
        public String64  ackTarget;
      };
      
    };
  };
};

#endif // rapid_ext_traclabs_NoticeAck_idl

