
/*
WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.

This file was generated from .idl using "rtiddsgen".
The rtiddsgen tool is part of the RTI Connext distribution.
For more information, type 'rtiddsgen -help' at a command shell
or consult the RTI Connext manual.
*/

package rapid.ext.arc;

import com.rti.dds.cdr.CdrEncapsulation;
import com.rti.dds.cdr.CdrInputStream;
import com.rti.dds.cdr.CdrOutputStream;
import com.rti.dds.cdr.CdrPrimitiveType;
import com.rti.dds.cdr.CdrBuffer;
import com.rti.dds.cdr.CdrHelper;
import com.rti.dds.cdr.CdrMemberInfo;
import com.rti.dds.domain.DomainParticipant;
import com.rti.dds.publication.DataWriter;
import com.rti.dds.publication.DataWriterListener;
import com.rti.dds.subscription.DataReader;
import com.rti.dds.subscription.DataReaderListener;
import com.rti.dds.topic.KeyHash_t;
import com.rti.dds.topic.TypeSupportImpl;
import com.rti.dds.topic.TypeSupportType;
import com.rti.dds.util.Sequence;
import com.rti.dds.topic.DefaultEndpointData;
import com.rti.dds.infrastructure.RETCODE_ERROR;

import com.rti.dds.infrastructure.*;
import com.rti.dds.topic.TypeSupportParticipantInfo;
import com.rti.dds.topic.TypeSupportEndpointInfo;
import com.rti.dds.typecode.TypeCode;
import com.rti.dds.cdr.IllegalCdrStateException;

import com.rti.dds.infrastructure.Copyable;

/**
* A collection of useful methods for dealing with objects of type
* Marker
*/

public class MarkerTypeSupport extends TypeSupportImpl {
    // -----------------------------------------------------------------------
    // Private Fields
    // -----------------------------------------------------------------------

    private static final String TYPE_NAME = "rapid::ext::arc::Marker";

    private static final char[] PLUGIN_VERSION = {2, 0, 0, 0};     
    private static final MarkerTypeSupport _singleton
    = new MarkerTypeSupport();

    // -----------------------------------------------------------------------
    // Public Methods
    // -----------------------------------------------------------------------

    // --- External methods: -------------------------------------------------
    /* The methods in this section are for use by users of RTI Connext
    */

    public static String get_type_name() {
        return _singleton.get_type_nameI();
    }

    public static void register_type(DomainParticipant participant,
    String type_name) {
        _singleton.register_typeI(participant, type_name);
    }

    public static void unregister_type(DomainParticipant participant,
    String type_name) {
        _singleton.unregister_typeI(participant, type_name);
    }

    /* The methods in this section are for use by RTI Connext
    * itself and by the code generated by rtiddsgen for other types.
    * They should be used directly or modified only by advanced users and are
    * subject to change in future versions of RTI Connext.
    */
    public static MarkerTypeSupport get_instance() {
        return _singleton;
    }

    public static MarkerTypeSupport getInstance() {
        return get_instance();
    }

    public static TypeCode getTypeCode(){
        return MarkerTypeCode.VALUE;
    }

    public Object create_data() {
        return Marker.create();
    }

    public void destroy_data(Object data) {
        return;
    }
    public Object create_key() {
        return new Marker();
    }

    public void destroy_key(Object key) {
        return;
    }
    public Class get_type() {
        return Marker.class;
    }

    /**
    * This is a concrete implementation of this method inherited from the base class.
    * This method will perform a deep copy of <code>source</code> into
    * <code>destination</code>.
    * 
    * @param src The Object which contains the data to be copied.
    * @return Returns <code>destination</code>.
    * @exception NullPointerException If <code>destination</code> or 
    * <code>source</code> is null.
    * @exception ClassCastException If either <code>destination</code> or
    * <code>this</code> is not a <code>Marker</code>
    * type.
    */
    public Object copy_data(Object destination, Object source) {

        Marker typedDst = (Marker) destination;
        Marker typedSrc = (Marker) source;

        return typedDst.copy_from(typedSrc);

    }

    public long get_serialized_sample_max_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        /** Namespace to place this object in... used in conjunction with id to create a unique name for the object */
        currentAlignment += CdrPrimitiveType.getStringMaxSizeSerialized(currentAlignment, (32)+1);
        /** object ID useful in conjunction with the namespace for manipulating and deleting the object later */
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        /** Type of object */
        currentAlignment += rapid.ext.arc.ShapeTypeTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects */
        currentAlignment += rapid.ext.arc.ActionTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** Pose of the object */
        currentAlignment += rapid.Transform3DTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** Scale of the object 1,1,1 means default (usually 1 meter square) */
        currentAlignment += rapid.Vec3fTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** RGBA color [0.0-1.0] */
        currentAlignment += rapid.Color4fTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** NS How long (in nanoseconds) the object should last before being automatically deleted.  0 means forever */
        currentAlignment += CdrPrimitiveType.LONG.getMaxSizeSerialized(currentAlignment );
        /** If this marker should be frame-locked, i.e. retransformed into its frame every timestep */
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );
        /** Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...) */
        currentAlignment += rapid.ext.arc.PointSequence1KTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);

        currentAlignment += rapid.ext.arc.ColorSequence1KTypeSupport.get_instance().get_serialized_sample_max_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /**  NOTE: only used for text markers */
        currentAlignment += CdrPrimitiveType.getStringMaxSizeSerialized(currentAlignment, (32)+1);
        /**  NOTE: only used for MESH_RESOURCE markers */
        currentAlignment += CdrPrimitiveType.getStringMaxSizeSerialized(currentAlignment, (32)+1);
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;
    }

    public long get_serialized_sample_min_size(Object endpoint_data,boolean include_encapsulation,short encapsulation_id,long currentAlignment) {

        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        /** Namespace to place this object in... used in conjunction with id to create a unique name for the object */
        currentAlignment += CdrPrimitiveType.getStringMaxSizeSerialized(currentAlignment, 1);
        /** object ID useful in conjunction with the namespace for manipulating and deleting the object later */
        currentAlignment += CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment );
        /** Type of object */
        currentAlignment += rapid.ext.arc.ShapeTypeTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects */
        currentAlignment += rapid.ext.arc.ActionTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** Pose of the object */
        currentAlignment += rapid.Transform3DTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** Scale of the object 1,1,1 means default (usually 1 meter square) */
        currentAlignment += rapid.Vec3fTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** RGBA color [0.0-1.0] */
        currentAlignment += rapid.Color4fTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /** NS How long (in nanoseconds) the object should last before being automatically deleted.  0 means forever */
        currentAlignment += CdrPrimitiveType.LONG.getMaxSizeSerialized(currentAlignment );
        /** If this marker should be frame-locked, i.e. retransformed into its frame every timestep */
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );
        /** Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...) */
        currentAlignment += rapid.ext.arc.PointSequence1KTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);

        currentAlignment += rapid.ext.arc.ColorSequence1KTypeSupport.get_instance().get_serialized_sample_min_size(endpoint_data,false, encapsulation_id,currentAlignment);
        /**  NOTE: only used for text markers */
        currentAlignment += CdrPrimitiveType.getStringMaxSizeSerialized(currentAlignment, 1);
        /**  NOTE: only used for MESH_RESOURCE markers */
        currentAlignment += CdrPrimitiveType.getStringMaxSizeSerialized(currentAlignment, 1);
        currentAlignment += CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment );

        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return  currentAlignment - origAlignment;

    }

    public long get_serialized_sample_size(
        Object endpoint_data, boolean include_encapsulation, 
        short encapsulation_id, long currentAlignment,
        Object sample) 
    {
        Marker typedSrc = (Marker) sample;
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        /** Namespace to place this object in... used in conjunction with id to create a unique name for the object */
        currentAlignment  +=  CdrPrimitiveType.getStringSerializedSize(currentAlignment , typedSrc.ns );
        /** object ID useful in conjunction with the namespace for manipulating and deleting the object later */
        currentAlignment  +=  CdrPrimitiveType.INT.getMaxSizeSerialized(currentAlignment);
        /** Type of object */
        currentAlignment += rapid.ext.arc.ShapeTypeTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.type);
        /** 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects */
        currentAlignment += rapid.ext.arc.ActionTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.action);
        /** Pose of the object */
        currentAlignment += rapid.Transform3DTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.pose);
        /** Scale of the object 1,1,1 means default (usually 1 meter square) */
        currentAlignment += rapid.Vec3fTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.scale);
        /** RGBA color [0.0-1.0] */
        currentAlignment += rapid.Color4fTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.color);
        /** NS How long (in nanoseconds) the object should last before being automatically deleted.  0 means forever */
        currentAlignment  +=  CdrPrimitiveType.LONG.getMaxSizeSerialized(currentAlignment);
        /** If this marker should be frame-locked, i.e. retransformed into its frame every timestep */
        currentAlignment  +=  CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment);
        /** Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...) */
        currentAlignment += rapid.ext.arc.PointSequence1KTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.points);

        currentAlignment += rapid.ext.arc.ColorSequence1KTypeSupport.get_instance().get_serialized_sample_size(
            endpoint_data,false,encapsulation_id,currentAlignment,typedSrc.colors);
        /**  NOTE: only used for text markers */
        currentAlignment  +=  CdrPrimitiveType.getStringSerializedSize(currentAlignment , typedSrc.text );
        /**  NOTE: only used for MESH_RESOURCE markers */
        currentAlignment  +=  CdrPrimitiveType.getStringSerializedSize(currentAlignment , typedSrc.mesh_resource );
        currentAlignment  +=  CdrPrimitiveType.BOOLEAN.getMaxSizeSerialized(currentAlignment);

        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }
        return currentAlignment - origAlignment;
    }

    public long get_serialized_key_max_size(
        Object endpoint_data,
        boolean include_encapsulation, 
        short encapsulation_id,
        long currentAlignment) 
    {
        long origAlignment = currentAlignment;
        long encapsulation_size = currentAlignment;

        if(include_encapsulation) {
            if (!CdrEncapsulation.isValidEncapsulationKind(encapsulation_id)) {
                throw new RETCODE_ERROR("Unsupported encapsulation");
            }

            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size += CdrPrimitiveType.SHORT.getMaxSizeSerialized(encapsulation_size);
            encapsulation_size -= currentAlignment;
            currentAlignment = 0;
            origAlignment = 0;

        } 

        currentAlignment += get_serialized_sample_max_size(
            endpoint_data,false,encapsulation_id,currentAlignment);
        if (include_encapsulation) {
            currentAlignment += encapsulation_size;
        }

        return currentAlignment - origAlignment;
    }

    public void serialize(Object endpoint_data,Object src, CdrOutputStream dst,boolean serialize_encapsulation,
    short encapsulation_id, boolean serialize_sample, Object endpoint_plugin_qos) {
        int position = 0;

        if(serialize_encapsulation) {
            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();

        }

        if(serialize_sample) {

            Marker typedSrc = (Marker) src;

            /** Namespace to place this object in... used in conjunction with id to create a unique name for the object */

            dst.writeString(typedSrc.ns,32);
            /** object ID useful in conjunction with the namespace for manipulating and deleting the object later */

            dst.writeInt(typedSrc.id);
            /** Type of object */

            rapid.ext.arc.ShapeTypeTypeSupport.get_instance().serialize(endpoint_data, typedSrc.type, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            /** 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects */

            rapid.ext.arc.ActionTypeSupport.get_instance().serialize(endpoint_data, typedSrc.action, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            /** Pose of the object */

            rapid.Transform3DTypeSupport.get_instance().serialize(endpoint_data, typedSrc.pose, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            /** Scale of the object 1,1,1 means default (usually 1 meter square) */

            rapid.Vec3fTypeSupport.get_instance().serialize(endpoint_data, typedSrc.scale, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            /** RGBA color [0.0-1.0] */

            rapid.Color4fTypeSupport.get_instance().serialize(endpoint_data, typedSrc.color, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            /** NS How long (in nanoseconds) the object should last before being automatically deleted.  0 means forever */

            dst.writeLong(typedSrc.lifetime);
            /** If this marker should be frame-locked, i.e. retransformed into its frame every timestep */

            dst.writeBoolean(typedSrc.frame_locked);
            /** Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...) */

            rapid.ext.arc.PointSequence1KTypeSupport.get_instance().serialize(endpoint_data, typedSrc.points, dst, false, encapsulation_id,true,endpoint_plugin_qos);

            rapid.ext.arc.ColorSequence1KTypeSupport.get_instance().serialize(endpoint_data, typedSrc.colors, dst, false, encapsulation_id,true,endpoint_plugin_qos);
            /**  NOTE: only used for text markers */

            dst.writeString(typedSrc.text,32);
            /**  NOTE: only used for MESH_RESOURCE markers */

            dst.writeString(typedSrc.mesh_resource,32);

            dst.writeBoolean(typedSrc.mesh_use_embedded_materials);
        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }

    }
    public long serialize_to_cdr_buffer(
        byte[] buffer,
        long length,
        Marker src)
    {
        return super.serialize_to_cdr_buffer(buffer,length,src);
    }

    public void serialize_key(
        Object endpoint_data,
        Object src,
        CdrOutputStream dst,
        boolean serialize_encapsulation,
        short encapsulation_id,
        boolean serialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        if (serialize_encapsulation) {
            dst.serializeAndSetCdrEncapsulation(encapsulation_id);

            position = dst.resetAlignment();
        }

        if (serialize_key) {

            Marker typedSrc = (Marker) src;    
            serialize(endpoint_data, src, dst, false, CdrEncapsulation.CDR_ENCAPSULATION_ID_CDR_BE, true, endpoint_plugin_qos);

        }

        if (serialize_encapsulation) {
            dst.restoreAlignment(position);
        }
    }

    public Object deserialize_sample(
        Object endpoint_data,
        Object dst, 
        CdrInputStream src, boolean deserialize_encapsulation,
        boolean deserialize_sample,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_sample) {

            Marker typedDst = (Marker) dst;
            typedDst.clear();      
            try{
                /** Namespace to place this object in... used in conjunction with id to create a unique name for the object */
                typedDst.ns = src.readString(32);
                /** object ID useful in conjunction with the namespace for manipulating and deleting the object later */
                typedDst.id = src.readInt();
                /** Type of object */
                typedDst.type = (rapid.ext.arc.ShapeType)rapid.ext.arc.ShapeTypeTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.type, src, false, true, endpoint_plugin_qos);     
                /** 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects */
                typedDst.action = (rapid.ext.arc.Action)rapid.ext.arc.ActionTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.action, src, false, true, endpoint_plugin_qos);     
                /** Pose of the object */
                typedDst.pose = (rapid.Transform3D)rapid.Transform3DTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.pose, src, false, true, endpoint_plugin_qos);     
                /** Scale of the object 1,1,1 means default (usually 1 meter square) */
                typedDst.scale = (rapid.Vec3f)rapid.Vec3fTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.scale, src, false, true, endpoint_plugin_qos);     
                /** RGBA color [0.0-1.0] */
                typedDst.color = (rapid.Color4f)rapid.Color4fTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.color, src, false, true, endpoint_plugin_qos);     
                /** NS How long (in nanoseconds) the object should last before being automatically deleted.  0 means forever */
                typedDst.lifetime = src.readLong();
                /** If this marker should be frame-locked, i.e. retransformed into its frame every timestep */
                typedDst.frame_locked = src.readBoolean();
                /** Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...) */
                typedDst.points = (rapid.ext.arc.PointSequence1K)rapid.ext.arc.PointSequence1KTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.points, src, false, true, endpoint_plugin_qos);     

                typedDst.colors = (rapid.ext.arc.ColorSequence1K)rapid.ext.arc.ColorSequence1KTypeSupport.get_instance().deserialize_sample(endpoint_data, typedDst.colors, src, false, true, endpoint_plugin_qos);     
                /**  NOTE: only used for text markers */
                typedDst.text = src.readString(32);
                /**  NOTE: only used for MESH_RESOURCE markers */
                typedDst.mesh_resource = src.readString(32);
                typedDst.mesh_use_embedded_materials = src.readBoolean();
            } catch (IllegalCdrStateException stateEx) {
                if (src.available() >= CdrEncapsulation.CDR_ENCAPSULATION_PARAMETER_ID_ALIGNMENT) {
                    throw new RETCODE_ERROR("Error deserializing sample! Remainder: " + src.available() + "\n" +
                    "Exception caused by: " + stateEx.getMessage());
                }
            } catch (Exception ex) {
                throw new RETCODE_ERROR(ex.getMessage());        
            }

        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void deserialize_from_cdr_buffer(
        Marker dst,
        byte[] buffer,
        long length) 
    {
        super.deserialize_from_cdr_buffer(dst,buffer,length);
    }

    public Object deserialize_key_sample(
        Object endpoint_data,
        Object dst,
        CdrInputStream src,
        boolean deserialize_encapsulation,
        boolean deserialize_key,
        Object endpoint_plugin_qos) 
    {
        int position = 0;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if(deserialize_key) {

            Marker typedDst = (Marker) dst;

            deserialize_sample(endpoint_data, dst, src, false, true, endpoint_plugin_qos);

        }
        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return dst;
    }

    public void skip(Object endpoint_data, 
    CdrInputStream src,
    boolean skip_encapsulation, 
    boolean skip_sample, 
    Object endpoint_plugin_qos)
    {
        int position = 0;

        if (skip_encapsulation) {
            src.skipEncapsulation();

            position = src.resetAlignment();
        }

        if (skip_sample) {

            /** Namespace to place this object in... used in conjunction with id to create a unique name for the object */
            src.skipString();

            /** object ID useful in conjunction with the namespace for manipulating and deleting the object later */
            src.skipInt();

            /** Type of object */
            rapid.ext.arc.ShapeTypeTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            /** 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects */
            rapid.ext.arc.ActionTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            /** Pose of the object */
            rapid.Transform3DTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            /** Scale of the object 1,1,1 means default (usually 1 meter square) */
            rapid.Vec3fTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            /** RGBA color [0.0-1.0] */
            rapid.Color4fTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            /** NS How long (in nanoseconds) the object should last before being automatically deleted.  0 means forever */
            src.skipLong();

            /** If this marker should be frame-locked, i.e. retransformed into its frame every timestep */
            src.skipBoolean();

            /** Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...) */
            rapid.ext.arc.PointSequence1KTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            rapid.ext.arc.ColorSequence1KTypeSupport.get_instance().skip(endpoint_data, src, false, true, endpoint_plugin_qos);

            /**  NOTE: only used for text markers */
            src.skipString();

            /**  NOTE: only used for MESH_RESOURCE markers */
            src.skipString();

            src.skipBoolean();

        }

        if (skip_encapsulation) {
            src.restoreAlignment(position);
        }
    }

    public Object serialized_sample_to_key(
        Object endpoint_data,
        Object sample,
        CdrInputStream src, 
        boolean deserialize_encapsulation,  
        boolean deserialize_key, 
        Object endpoint_plugin_qos) 
    {

        int position = 0;

        if(deserialize_encapsulation) {
            src.deserializeAndSetCdrEncapsulation();

            position = src.resetAlignment();
        }

        if (deserialize_key) {

            Marker typedDst = (Marker) sample;

            deserialize_sample(
                endpoint_data, sample, src, false,
                true, endpoint_plugin_qos);

        }

        if (deserialize_encapsulation) {
            src.restoreAlignment(position);
        }

        return sample;
    }

    // -----------------------------------------------------------------------
    // Callbacks
    // -----------------------------------------------------------------------
    public Object on_participant_attached(Object registration_data,
    TypeSupportParticipantInfo participant_info,
    boolean top_level_registration,
    Object container_plugin_context,
    TypeCode type_code) {
        return super.on_participant_attached(
            registration_data, participant_info, top_level_registration,
            container_plugin_context, type_code);
    }

    public void on_participant_detached(Object participant_data) {
        super.on_participant_detached(participant_data);
    }

    public Object on_endpoint_attached(Object participantData,
    TypeSupportEndpointInfo endpoint_info,
    boolean top_level_registration,
    Object container_plugin_context) {
        return super.on_endpoint_attached(
            participantData,  endpoint_info,  
            top_level_registration, container_plugin_context);        
    }

    public void on_endpoint_detached(Object endpoint_data) {
        super.on_endpoint_detached(endpoint_data);
    }
    // -----------------------------------------------------------------------
    // Protected Methods
    // -----------------------------------------------------------------------

    protected DataWriter create_datawriter(long native_writer,
    DataWriterListener listener,
    int mask) {
        return new MarkerDataWriter (native_writer, listener, mask, this);            
    }

    protected DataReader create_datareader(long native_reader,
    DataReaderListener listener,
    int mask) {

        return new MarkerDataReader(native_reader, listener, mask, this);   

    }

    // -----------------------------------------------------------------------
    // Constructor
    // -----------------------------------------------------------------------

    protected MarkerTypeSupport() {

        /* If the user data type supports keys, then the second argument
        to the constructor below should be true.  Otherwise it should
        be false. */        

        super(TYPE_NAME, false,MarkerTypeCode.VALUE,Marker.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);

    }

    protected MarkerTypeSupport (boolean enableKeySupport) {

        super(TYPE_NAME, enableKeySupport,MarkerTypeCode.VALUE,Marker.class,TypeSupportType.TST_STRUCT, PLUGIN_VERSION);
    }
}

